FROM node:lts-alpine AS builder
WORKDIR /app
COPY *.json .
COPY *.html .
COPY *.ts .
RUN npm install
RUN npm install -g typescript
COPY src/ src/
COPY public/ public/
RUN ["npm", "run", "build"]

FROM nginx:stable-alpine
RUN rm -f /etc/nginx/conf.d/default.conf
COPY default.conf.template /etc/nginx/templates/
COPY --from=builder /app/dist /usr/share/nginx/html
