FROM node:lts-alpine AS builder
WORKDIR /app
COPY ../../frontend/*.json .
COPY ../../frontend/*.html .
COPY ../../frontend/*.ts .
RUN npm install
RUN npm install -g typescript
COPY ../../frontend/src/ src/
COPY ../../frontend/public/ public/
RUN ["npm", "run", "build"]

FROM nginx:stable-alpine
RUN rm -f /etc/nginx/conf.d/default.conf
COPY _env/stg/nginx/default.conf.template /etc/nginx/templates/
COPY --from=builder /app/dist /usr/share/nginx/html
